apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: aws-billing-to-slack
  description: Catalog entities for aws-billing-to-slack.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
